Logical: EHDSDischargeReport
Parent: EHDSDocument
Title: "Discharge Report model"
Description: """A generic, flexible model for any kind of discharge report. Different types of encounters may require adding relevant sections and elements, or omitting irrelevant ones, depending on their data needs."""


* header // Obligations inherited from EHDSDocument
  * ^short = "Discharge report header." //TODO All others are Document header.
  * ^definition = "Discharge report header."
  * status
  * identifier
  * author[x]
  * documentType
    * ^short = "Type of document, e.g. 34105-7 Hospital discharge summary."
    * ^definition = "Type of document, e.g. 34105-7 Hospital discharge summary."
  * documentTitle
    * ^short = "Human readable document title that can be displayed in search results, etc. This can be documentType’s display name or it can contain further information. Example: 'Hospital discharge report. Jane Green. 07.10.2025-10.10.2025'."
    * ^definition = "Title of the document, possibly autogenerated from the structured fields (e.g. 'Hospital discharge report. Jane Green. 07.10.2025-10.10.2025')"
  * period 
    * ^definition = "Time of service that is being documented (typically the same as the time/period of the encounter)."
  * eventCategory
    * ^binding.description = "SNOMED CT (preferred), LOINC"
    * ^binding.strength = #required
    * ^short = "Categorisation of the event covered by the document (e.g. discharge type). Selection of such tags or labels depends on the use case and agreement between data sharing parties. This meta-data element serves primarily for searching and filtering purposes."
    * ^definition = "Categorisation of the event covered by the document (e.g. discharge type). Selection of such tags or labels depends on the use case and agreement between data sharing parties. This meta-data element serves primarily for searching and filtering purposes."
  * intendedRecipient[x] 0..* EHDSRelatedPerson or EHDSHealthProfessional or EHDSOrganisation "Intended recipient of the information, i.e. a person or organisation that should be notified or be aware of the content. This element is used to indicate explicit communication intent and does not represent routine storage or passive availability of information (e.g. in portals). Listing an intended recipient does not create an assignment or responsibility."
    * insert Full(#SHOULD)
    * insert Basic(#SHOULD)
* body 0..1 Base "Discharge report structured body."
  * insert Full(#SHALL)
  * insert Basic(#SHALL)
  * alerts 0..1 Base "Section: Alerts." "Information about substantial alerts or warnings (including allergies) that health professionals should be aware of."
    * insert Full(#SHOULD)
    * insert Basic(#SHOULD)
    * generatedNarrative 0..1 Narrative "Narrative, potentially formatted, content of the whole section."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * medicalAlert 0..* EHDSAlert "Description of medical alerts in textual format: any clinical information that is imperative to know so that the life or health of the patient does not come under threat."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
  * encounterInformation 1..1 Base "Section: Encounter information."
    * insert Full(#SHALL)
    * insert Basic(#SHALL)
    * generatedNarrative 0..1 Narrative "Narrative, potentially formatted, content of the whole section."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * encounter 1..1 EHDSEncounter "Encounter information"
      * insert Full(#SHALL)
      * insert Basic(#SHALL)
    * note 0..1 string "Free text notes by the health professional."
      * insert Full(#SHALL) // TODO Check obligations. 
      * insert Basic(#SHOULD)

  * admissionEvaluation 0..1 Base "Section: Admission evaluation. Admission evaluation section should be reported only if it is relevant to ensure continuity of care."
    * insert Full(#SHALL)
    * insert Basic(#SHALL)
    * generatedNarrative 0..1 Narrative "Narrative, potentially formatted, content of the whole section."
      * insert Full(#SHALL)
      * insert Basic(#SHALL)
    * objectiveFindings 0..* EHDSObservation "Objective findings, such as anthropometric measurements, vital signs, or objective anatomical findings of physical examination."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * functionalStatus[x] 0..* EHDSCondition or EHDSObservation "An individual's ability to perform normal daily activities required to meet basic needs, fulfil usual roles and maintain health and well-being"
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * note 0..1 string "Free text notes by the evaluation performer."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)

  * patientHistory 0..1 Base "Section: Patient health history (anamnesis) containing only information that is highly relevant for this specific episode of care. The model is designed with the expectation that patient summary is available."
    * insert Full(#SHALL)
    * insert Basic(#SHOULD)
    * generatedNarrative 0..1 Narrative "Narrative, potentially formatted, content of the whole section. In case the section includes structured information, it should also be included in generatedNarrative."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD) 
    * pastProblems[x] 0..* EHDSCondition or EHDSObservation "A list of conditions of a patient that the patient suffered in the past or still suffers. Unlike diagnostic summary, medical history is not only a list of problems, but could contain broader description of the condition and its progress, details about treatment including medication and patient response to treatment. Past problem section (unlike the same section of the patient summary) should include only conditions that are important for continuity of care. This section, if provided, complements the diagnostic summary section of the discharge report."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)    
    * devicesAndImplants 0..* EHDSDeviceUse "Devices and implants in patient anamnesis."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * procedures 0..* EHDSProcedure "Procedures in patient anamnesis." "Historical procedures performed on or for a patient, relevant for the current encounter."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD) 
    * note 0..1 string "Free text notes by the health professional."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)

  * courseOfEncounter 1..1 Base "Section: Course of inpatient or outpatient encounter."
    * insert Full(#SHALL)
    * insert Basic(#SHALL)
    * generatedNarrative 0..1 Narrative "Narrative, potentially formatted, content of the whole section."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * conditionSummary 1..* EHDSCondition "Conditions that were treated or affected provisioning of care (diagnostics, therapy, nursing, monitoring) during the encounter. At least one attended condition should be marked. Other conditions are recorded only if they are important for continuity of care (after discharge)."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * procedures 0..* EHDSProcedure "Procedures performed during encounter which are significant for continuity of care, e.g. surgeries and other instrumental interventions (endoscopic, intravascular), chemotherapy, radiotherapy, purification methods (dialysis, hemoperfusion), circulation support methods (counterpulsation, etc.), administration of blood derivatives or others. Diagnostic procedures are typically captured as observation results and not repeated here."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * medicalDevicesAndImplants 0..* EHDSDeviceUse "Medical devices (including implants) whose use was started, stopped, or otherwise modified during the encounter."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * pharmacotherapy 0..* EHDSMedicationUse "Significant medication treatments during encounter."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * objectiveFindings 0..* EHDSObservation "Objective findings, such as anthropometric measurements, vital signs, or objective anatomical findings of physical examination. The line between objective findings and test results is not clear and it is up to the implementers to decide how to logically display different measurements."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * testResults[x] 0..* EHDSObservation or EHDSLaboratoryObservation "Significant medical test results of functional, diagnostic (including laboratory), and imaging examinations performed during encounter."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
      * ^comment = "This may include orders for which the results have not yet arrived."
    * note 0..1 string "Free text notes by the health professional."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)

  * dischargeDetails 0..1 Base "Section: Discharge details."
    * insert Full(#SHALL)
    * insert Basic(#SHOULD)
    * generatedNarrative 0..1 Narrative "Narrative, potentially formatted, content of the whole section."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * objectiveFindings 0..* EHDSObservation "Objective findings, such as anthropometric measurements, vital signs, or objective anatomical findings of physical examination."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * functionalStatus[x] 0..* EHDSCondition or EHDSObservation "An individual's ability to perform normal daily activities required to meet basic needs, fulfil usual roles and maintain health and well-being."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * note 0..1 string "Free text notes by the health professional."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)

  * medicationSummary 0..1 Base "Summary information on the medication recommended for the period after discharge, indicating whether the medication is changed or newly started. Compared to previous practices, the overview is supplemented with medication that has been discontinued."
    * insert Full(#SHALL)
    * insert Basic(#SHALL)
    * generatedNarrative 0..1 Narrative "Narrative, potentially formatted, content of the whole section."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * medicationUse 0..* EHDSMedicationUse "Details about medication and dosage"
      * insert Full(#SHALL)
      * insert Basic(#SHALL)
    * note 0..1 string "Free text notes by the health professional."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)

  * carePlan 0..1 Base "Section: Care plan and other recommendations after discharge."
    * insert Full(#SHALL)
    * insert Basic(#SHALL)
    * generatedNarrative 0..1 Narrative "Narrative, potentially formatted, content of the whole section."
      * insert Full(#SHALL)
      * insert Basic(#SHALL)
    * structuredCarePlan 0..* EHDSCarePlan "Structured care plan after discharge."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
    * otherRecommendations 0..1 string "Other recommendations (advice) after discharge. E.g., recommendation to suggest hip replacement, reduce number of cigarettes, stop smoking, increase physical exercises, etc."
      * insert Full(#SHALL)
      * insert Basic(#SHOULD)
//  * synthesis 0..1 string "Clinical synthesis (e.g. description of reasons and course of encounter) clustered by managed conditions. Clinical synthesis may include clinical reasoning (differential diagnostics, explanation of clinical context) in clinically complex conditions."
* attachment 0..* EHDSAttachment "Report attachment."
  * insert Full(#SHALL)
  * insert Basic(#SHALL)