Logical: EHDSImagingReport
Title: "Imaging report model"
Parent: EHDSDocument
Description: """Imaging report reflects the observations and interpretations of one or more imaging studies, contains elements such as the reason why the study is requested, relevant contextual medical information, the modality used to acquire images and its settings, procedures and body localisations that were used, a description of the observations and findings, exposure information, conclusion and advice."""

* header ^short = "Imaging report header"
  * status
  * author[x]
  * documentType
    * ^short = "Type of document (e.g. 18748-4 Diagnostic imaging study)."
    * ^definition = "Type of document (e.g. 18748-4 Diagnostic imaging study)."
  * documentTitle
    * ^short = "Human readable document title that can be displayed in search results, etc. This can be documentType's display name, or it can be assembled from multiple elements."
    * ^definition = "Human readable document title that can be displayed in search results, etc. This can be documentType's display name, or it can be assembled from multiple elements."
  * eventCategory
    * ^short = "Categorisation of the event covered by the document (e.g. imaging study types, body regions, modality, etc.). Selection of such tags or labels depends on the use case and agreement between data sharing parties. This meta-data element serves primarily for searching and filtering purposes."
    * ^definition = "Categorisation of the event covered by the document (e.g. imaging study types, body regions, modality, etc.). Selection of such tags or labels depends on the use case and agreement between data sharing parties. This meta-data element serves primarily for searching and filtering purposes."
  * accessionNumber 0..* Identifier "Accession number - an identifier, managed by the RIS at the local level, which usually uniquely identifies an imaging procedure request, and links it to imaging study and related imaging report."
    * ^requirements = "eHN Guideline IMG (v1.1): A.1.8.11"
  * intendedRecipient[x] 0..* EHDSPatient or EHDSRelatedPerson or EHDSHealthProfessional or EHDSOrganisation "Information recipient (intended recipient of the report, additional recipients might be identified by the ordering party, e.g. GP, other specialist), if applicable."
    * ^requirements = "eHN Guideline IMG (v1.1): A.1.4"
* body 0..1 Base "Imaging report structured body."
  * orderInformation 0..* Base "Order to which this imaging report is linked."
    * ^requirements = "eHN Guideline IMG (v1.1): A.2"
    * orderId 1..* Identifier "Identifier of the imaging service order."
    * orderDateAndTime 0..1 dateTime "Date and time of the order placement."
    * orderPlacer[x] 0..1 EHDSHealthProfessional or EHDSOrganisation or EHDSPatient "The person/organisation authorised to place the order."
    * orderReason[x] 0..* CodeableConcept or EHDSCondition or EHDSObservation or string "An explanation or justification for why this service is being requested."
      * ^binding.description = "SNOMED CT"
      * ^binding.strength = #preferred
      * ^requirements = "eHN Guideline IMG (v1.1): A.3.1, A3.2"
    * clinicalQuestion 0..1 string "Specification of clinical question (goal of the investigation) to be answered by the imaging investigation."
      * ^requirements = "eHN Guideline IMG (v1.1): A.3.3"
  * supportingInformation 0..1 Base "Additional clinical information about the patient or specimen that may affect service delivery or interpretation (additional types of information may be allowed in implementations)." """This information includes diagnosis, clinical findings and other observations. This includes observations explicitly requested by the producer (filler) to provide context or supporting information needed to complete the order. For example, reporting the metal implants present in patient's body."""
    * ^requirements = "eHN Guideline IMG (v1.1): A3.2?"
    * observation 0..* EHDSObservation "Clinical findings and other observations (e.g., height and weight of the patient)."
    * condition 0..* EHDSCondition "Condition that may influence the service or result interpretation."
    * priorMedicationAdministration 0..* EHDSMedicationAdministration "Medication administered before ordering the service that may influence the service or result interpretation."
    // TODO check final wording. "Medication administered before ordering the service specifically for this procedure."
    * device 0..* EHDSDeviceUse "List of implants or devices that affect the course of the examination or its interpretation (e.g. metal implants)."
    * pregnancyStatus 0..1 EHDSCurrentPregnancyStatus "Pregnancy status when the imaging examination was performed (e.g., pregnant, not pregnant, unknown)."
  //  * sexForClinicalUse 0..1 CodeableConcept "Sex parameter for clinical use - provides guidance on how a recipient should apply settings or reference ranges that are derived from observable information such as an organ inventory, recent hormone lab tests, genetic testing, menstrual status, obstetric history, etc. This property is intended for use in clinical decision making, and indicates that treatment or diagnostic tests should consider best practices associated with the relevant reference population."
  //    * ^binding.description = "HL7 sex-parameter-for-clinical-use"
  //    * ^binding.strength = #preferred
  * specimen 0..* EHDSSpecimen "Specimen information."
    * ^requirements = "eHN Guideline IMG (v1.1): A.4"
    * ^comment = "A specimen (not attached to a body) can be used for diagnostic, forensic and medical research purposes."
  // TODO check whether serviceRequest is in or out. Add back if necessary.
  * exposureInformation 0..1 string "Information on total exposure during the imaging investigation to ionising radiation."
    * ^comment = "This information is required by regulations in several EU countries."
    * ^requirements = "eHN Guideline IMG (v1.1): B.1.4.4, Article 2 Imaging report definition"
  * examinationReport 1..1 Base "Examination report content."
    * ^requirements = "eHN Guideline IMG (v1.1): A.5"
    * modality 1..* CodeableConcept "Imaging modality used during imaging investigation (DICOM CID029)."
      * ^requirements = "eHN Guideline IMG (v1.1): A.5.1.1"
      * ^binding.description = "DICOM Modality"
      * ^binding.strength = #preferred
    * bodySite 0..* EHDSBodyStructure "Body part investigated."
      * ^requirements = "eHN Guideline IMG (v1.1): A.5.1.6"
    * imagingProcedure 0..* EHDSProcedure "Imaging procedure performed during imaging study."
      * ^requirements = "eHN Guideline IMG (v1.1): A.5.1.2-A.5.1.9"
    * medicationAdministration 0..* EHDSMedicationAdministration "Information about medications administered (contrast, sedation, stress agents, etc) to enable the imaging investigation or during it."
      * ^requirements = "eHN Guideline IMG (v1.1): A.5.2"
    * adverseReaction 0..* EHDSAllergyIntolerance "Adverse reaction manifested during imaging investigation."
      * ^requirements = "eHN Guideline IMG (v1.1): A.5.3"
    * result[x] 0..* EHDSObservation or string "Imaging report result data."
      * ^requirements = "eHN Guideline IMG (v1.1): A.5.4, A.5.4.1, A.5.4.3"
    * conclusion 0..1 Base "A concise and clinically contextualised summary including interpretation/impression of the diagnostic report."
      * ^requirements = "eHN Guideline IMG (v1.1): A.5.5"
      * impression 1..1 string "Narrative description of the clinical conclusion (impression)."
        * ^requirements = "eHN Guideline IMG (v1.1): A.5.5.1"
      * conditionOrFinding[x] 0..* EHDSCondition or EHDSObservation "Condition or finding from imaging investigation."
        * ^requirements = "eHN Guideline IMG (v1.1): A.5.5.2"
  * recommendation 0..1 Base "Recommendation section for additional imaging investigations or other actions."
    * ^requirements = "eHN Guideline IMG (v1.1): A.5.6"
    * description 1..1 string "Narrative description of the recommended activities including additional investigation, medication etc."
      * ^requirements = "eHN Guideline IMG (v1.1): A.5.6.1"
    * carePlan 0..* EHDSCarePlan "A complex and structured information about recommended goals, activities and objectives in the form of one or more formal care plan."
      * ^requirements = "eHN Guideline IMG (v1.1): A.5.6.2"
  * comparisonStudy 0..* EHDSImagingReport "Documentation (reference) of a prior Imaging Report to which the current images were compared."
    * ^requirements = "eHN Guideline IMG (v1.1): A.7"
* dicomStudyMetadata 0..* EHDSImagingStudy "Metadata of the DICOM study. A study comprises a set of series, each of which includes a set of Service-Object Pair Instances (SOP Instances - images or other data) acquired or produced in a common context. A series is of only one modality (e.g. X-ray, CT, MR, ultrasound), but a study may have multiple series of different modalities."
  * ^requirements = "eHN Guideline IMG (v1.1): A.6"
* attachments 0..* EHDSAttachment "Report attachments"